#!/bin/bash

aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_postulante_name'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_postulante_doctype'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_postulante_id'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_vereda'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_municipio'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_matricula'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='A_ficha_catastral'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='B_owner'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='B_owner_doctype'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='B_owner_id'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='B_owner_certificado'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='C_ubicacion'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='C_plano_predio'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='D_area'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='D_actual_use'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='E_restriccion_desc'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='E_resctriccion_other'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='F_nacimiento_agua'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='G_habita_predio'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='H_asistance_desc'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='H_aliados_estrategicos_desc'"
aws dynamodb execute-statement --statement "DELETE  FROM \"Feature-d6sfnut2zrdljfaz3ysbjfhvke-dev\" WHERE id='H_grupo_comunitario_desc'"